server:
  port: 8000
spring:
  application:
    name: article
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.130:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 1234
  servlet:
   multipart:
     max-file-size: 50MB
     max-request-size: 100MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.article

knife4j:
  enable: true



