server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.130:8848
    gateway:
      routes:
        - id: article
          uri: lb://article
          predicates:
            - Path=/article/**, /category/**,/file/**,/tag/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/link/**,/user/**
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有路径
            allowedOrigins: # 允许访问的源
              - "http://localhost:5173"
            allowedMethods: # 允许的HTTP方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: # 允许在请求中携带的头信息
              - "*"
            allowCredentials: true # 是否允许携带cookie
            maxAge: 3600 # 预检请求的缓存时间(秒)


